### ISSUE TITLE
[Diverge] Lid-driven flow, Re=100, Non-uniform grid (1000x1000)

### ISSUE THREAD

**Issue by piyueh** [barbagroup/PetIBM#71]
In the example of 2D lid-driven flow of Re=100 and non-uniform grid, when I increased the grid number, for example,

```
- direction: x
  start: 0.0
  subDomains:
      - end: 0.5
        cells: 500
        stretchRatio: 1.1
      - end: 1.0
        cells: 500
        stretchRatio: 0.90909090909090909

- direction: y
  start: 0.0
  subDomains:
      - end: 0.5
        cells: 500
        stretchRatio: 1.1
      - end: 1.0
        cells: 500
        stretchRatio: 0.90909090909090909
```

the Poisson solver diverged, no matter what kind of solvers I used (e.g. cg, bcgs) and no matter what kind of preconditioners I used (e.g. ilu, gamg, hypre). Different divergence reasons appeared according to different set of solvers and preconditioners. So far I've seen these error codes:
- -4: KSP_DIVERGED_DTOL
- -8: KSP_DIVERGED_INDEFINITE_PC
- -10: KSP_DIVERGED_INDEFINITE_MAT
- -11: KSP_DIVERGED_PCSETUP_FAILED

It's still not clear what happened or whether the problem comes from numerical methods, bugs in our codes, or bugs from PETSc. 

The PetIBM branch I used is `AmgXSolver`, and the PETSc version is git version at commit `dc32dc7981db1b5de6c76d77864ff05c0a7bb516`.
